options:
  port:
    type: int
    default: 5000
    description: HTTP port
  ui:
    type: string
    default: default
    description: Which UI to use
  url-prefix:
    type: string
    default: /jupyter
    description: URL prefix for HTTP requests
  backend-mode:
    type: string
    default: development
    description: Which mode out of `development` or `production` the backend server should use
  secure-cookies:
    type: boolean
    default: false
    description: Whether cookies should require HTTPS
  default_notebook_lists:
    type: string
    default: "default"
    description: |
      Comma separated list of available jupyter notebook urls. The default list is the following:
      - gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0
      - gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-gpu:1.0.0
      - gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-cpu:1.0.0
      - gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-gpu:1.0.0
